// app/lib/cities.ts

export const CITY_WHITELIST = [
  "duesseldorf",
  "meerbusch",
  "ratingen",
  "bergisch-gladbach",
  "pulheim",
  "rheda-wiedenbrueck",
  "langenfeld",
  "erkrath",
  "kaarst",
  "bad-oeynhausen",
  "willich",
  "koenigswinter",
  "arnsberg",
  "warendorf",
  "hilden",
  "haan",
  "guetersloh",
  "menden",
  "erftstadt",
  "herford",
  "kempen",
  "korschenbroich",
  "borken",
  "mettmann",
  "haltern-am-see",
  "sundern",
  "muenster",
  "bornheim",
  "rietberg",
  "bocholt",
  "wermelskirchen",
  "neuss",
  "bonn",
  "herdecke",
  "bad-honnef",
  "koeln",
  "roesrath",
  "olpe",
  "hennef-sieg",
  "muelheim-an-der-ruhr",
  "unna",
  "emsdetten",
  "sprockhoevel",
  "leichlingen",
  "dinslaken",
  "ahaus",
  "solingen",
  "lohmar",
  "verl",
  "huerth",
  "coesfeld",
  "bruehl",
  "sankt-augustin",
  "buende",
  "schwerte",
  "schloss-holte-stukenbrock",
  "wetter-ruhr",
  "delbrueck",
  "porta-westfalica",
  "wiehl",
  "duelmen",
  "luedinghausen",
  "meckenheim",
  "kreuztal",
  "hamminkeln",
  "meschede",
  "iserlohn",
  "oelde",
  "frechen",
  "rheine",
  "niederkassel",
  "toenisvorst",
  "bielefeld",
  "detmold",
  "wachtberg",
  "grevenbroich",
  "erkelenz",
  "hattingen",
  "overath",
  "warstein",
  "bad-salzuflen",
  "attendorn",
  "greven",
  "lippstadt",
  "dorsten",
  "ennepetal",
  "velbert",
  "dormagen",
  "leverkusen",
  "meinerzhagen",
  "alfter",
  "wilnsdorf",
  "wegberg",
  "siegen",
  "werne",
  "schmallenberg",
  "steinhagen",
  "vreden",
  "luebbecke",
  "witten",
  "schwelm",
  "steinfurt",
  "rheinbach",
  "recklinghausen",
  "brilon",
  "geldern",
  "luedenscheid",
  "telgte",
  "lemgo",
  "soest",
  "engelskirchen",
  "wesel",
  "xanten",
  "remscheid",
  "juelich",
  "warburg",
  "heiligenhaus",
  "burbach",
  "odenthal",
  "moers",
  "krefeld",
  "viersen",
  "minden",
  "froendenberg-ruhr",
  "lennestadt",
  "wuelfrath",
  "hemer",
  "kevelaer",
  "neunkirchen-seelscheid",
  "siegburg",
  "ahlen",
  "rhede",
  "wuerselen",
  "beckum",
  "loehne",
  "paderborn",
  "essen",
  "senden",
  "rheinberg",
  "nottuln",
  "moenchengladbach",
  "burscheid",
  "troisdorf",
  "bottrop",
  "drensteinfurt",
  "freudenberg",
  "kuerten",
  "juechen",
  "swisttal",
  "neukirchen-vluyn",
  "kerpen",
  "versmold",
  "hoexter",
  "waltrop",
  "stadtlohn",
  "aachen",
  "erwitte",
  "lindlar",
  "ibbenbueren",
  "bad-berleburg",
  "halle",
  "wipperfuerth",
  "enger",
  "bergheim",
  "gevelsberg",
  "oerlinghausen",
  "vlotho",
  "finnentrop",
  "nettetal",
  "hille",
  "wenden",
  "selm",
  "mechernich",
  "netphen",
  "schwalmtal",
  "radevormwald",
  "straelen",
  "plettenberg",
  "hiddenhausen",
  "wuppertal",
  "ennigerloh",
  "castrop-rauxel",
  "kamen",
  "kreuzau",
  "windeck",
  "bad-muenstereifel",
  "salzkotten",
  "much",
  "petershagen",
  "bochum",
  "holzwickede",
  "bad-wuennenberg",
  "herzogenrath",
  "gummersbach",
  "huenxe",
  "lengerich",
  "bedburg",
  "heinsberg",
  "blomberg",
  "herzebrock-clarholz",
  "marl",
  "euskirchen",
  "brueggen",
  "schermbeck",
  "simmerath",
  "hoerstel",
  "harsewinkel",
  "monheim-am-rhein",
  "dortmund",
  "halver",
  "hoevelhof",
  "moehnesee",
  "sendenhorst",
  "ascheberg",
  "nuembrecht",
  "gronau",
  "stolberg",
  "voerde-niederrhein",
  "rommerskirchen",
  "kirchhundem",
  "niederkruechten",
  "zuelpich",
  "dueren",
  "kerken",
  "borchen",
  "billerbeck",
  "weilerswist",
  "bueren",
  "marsberg",
  "geilenkirchen",
  "bad-sassendorf",
  "hagen",
  "neuenkirchen",
  "winterberg",
  "goch",
  "huellhorst",
  "elsdorf",
  "rees",
  "oberhausen",
  "lage",
  "eschweiler",
  "datteln",
  "hamm",
  "raesfeld",
  "grefrath",
  "brakel",
  "hilchenbach",
  "reichshof",
  "reken",
  "ochtrup",
  "herten",
  "spenge",
  "havixbeck",
  "alpen",
  "langerwehe",
  "werther",
  "hueckeswagen",
  "werl",
  "wesseling",
  "monschau",
  "rahden",
  "kalletal",
  "geseke",
  "luenen",
  "drolshagen",
  "ense",
  "stemwede",
  "velen",
  "leopoldshoehe",
  "schalksmuehle",
  "olsberg",
  "altenberge",
  "balve",
  "neuenrade",
  "bad-driburg",
  "kirchlengern",
  "olfen",
  "bad-laasphe",
  "gescher",
  "preussisch-oldendorf",
  "steinheim",
  "neunkirchen",
  "wassenberg",
  "altena",
  "kamp-lintfort",
  "gladbeck",
  "baesweiler",
  "nordkirchen",
  "herne",
  "uebach-palenberg",
  "everswinkel",
  "ostbevern",
  "nideggen",
  "beverungen",
  "sassenberg",
  "horn-bad-meinberg",
  "eitorf",
  "issum",
  "wadersloh",
  "linnich",
  "bergneustadt",
  "roetgen",
  "kalkar",
  "hueckelhoven",
  "lichtenau",
  "niederzier",
  "lippetal",
  "kierspe",
  "bergkamen",
  "rosendahl",
  "kleve",
  "mettingen",
  "suedlohn",
  "espelkamp",
  "anroechte",
  "westerkappeln",
  "welver",
  "oer-erkenschwick",
  "ruethen",
  "emmerich-am-rhein",
  "bad-lippspringe",
  "duisburg",
  "roedinghausen",
  "boenen",
  "tecklenburg",
  "noervenich",
  "schleiden",
  "ruppichteroth",
  "kall",
  "bedburg-hau",
  "eslohe",
  "waldbroel",
  "marienheide",
  "borgholzhausen",
  "huertgenwald",
  "morsbach",
  "nordwalde",
  "titz",
  "langenberg",
  "alsdorf",
  "breckerfeld",
  "borgentreich",
  "extertal",
  "heek",
  "heiden",
  "legden",
  "sonsbeck",
  "merzenich",
  "lotte",
  "werdohl",
  "bestwig",
  "gelsenkirchen",
  "wickede-ruhr",
  "recke",
  "schoeppingen",
  "wachtendonk",
  "luegde",
  "lienen",
  "gangelt",
  "altenbeken",
  "herscheid",
  "aldenhoven",
  "hopsten",
  "vettweiss",
  "wettringen",
  "schlangen",
  "uedem",
  "waldfeucht",
  "hellenthal",
  "saerbeck",
  "isselburg",
  "nettersheim",
  "ladbergen",
  "erndtebrueck",
  "nachrodt-wiblingwerde",
  "medebach",
  "barntrup",
  "blankenheim",
  "laer",
  "rheurdt",
  "schieder-schwalenberg",
  "selfkant",
  "doerentrup",
  "willebadessen",
  "weeze",
  "nieheim",
  "inden",
  "beelen",
  "horstmar",
  "augustdorf",
  "marienmuenster",
  "kranenburg",
  "hallenberg",
  "metelen",
  "dahlem",
  "heimbach",
] as const;

export type CitySlug = (typeof CITY_WHITELIST)[number];

export const CITY_SET = new Set<string>(CITY_WHITELIST);

/**
 * Exakte Anzeigenamen pro City-Slug – 100% korrekt, keine “ss/ß”-Fehler.
 */
export const CITY_LABELS: Record<CitySlug, string> = {
  duesseldorf: "Düsseldorf",
  meerbusch: "Meerbusch",
  ratingen: "Ratingen",
  "bergisch-gladbach": "Bergisch Gladbach",
  pulheim: "Pulheim",
  "rheda-wiedenbrueck": "Rheda-Wiedenbrück",
  langenfeld: "Langenfeld (Rhld.)",
  erkrath: "Erkrath",
  kaarst: "Kaarst",
  "bad-oeynhausen": "Bad Oeynhausen",
  willich: "Willich",
  koenigswinter: "Königswinter",
  arnsberg: "Arnsberg",
  warendorf: "Warendorf",
  hilden: "Hilden",
  haan: "Haan",
  guetersloh: "Gütersloh",
  menden: "Menden (Sauerland)",
  erftstadt: "Erftstadt",
  herford: "Herford",
  kempen: "Kempen",
  korschenbroich: "Korschenbroich",
  borken: "Borken",
  mettmann: "Mettmann",
  "haltern-am-see": "Haltern am See",
  sundern: "Sundern (Sauerland)",
  muenster: "Münster",
  bornheim: "Bornheim",
  rietberg: "Rietberg",
  bocholt: "Bocholt",
  wermelskirchen: "Wermelskirchen",
  neuss: "Neuss",
  bonn: "Bonn",
  herdecke: "Herdecke",
  "bad-honnef": "Bad Honnef",
  koeln: "Köln",
  roesrath: "Rösrath",
  olpe: "Olpe",
  "hennef-sieg": "Hennef (Sieg)",
  "muelheim-an-der-ruhr": "Mülheim an der Ruhr",
  unna: "Unna",
  emsdetten: "Emsdetten",
  sprockhoevel: "Sprockhövel",
  leichlingen: "Leichlingen (Rhld.)",
  dinslaken: "Dinslaken",
  ahaus: "Ahaus",
  solingen: "Solingen",
  lohmar: "Lohmar",
  verl: "Verl",
  huerth: "Hürth",
  coesfeld: "Coesfeld",
  bruehl: "Brühl",
  "sankt-augustin": "Sankt Augustin",
  buende: "Bünde",
  schwerte: "Schwerte",
  "schloss-holte-stukenbrock": "Schloß Holte-Stukenbrock",
  "wetter-ruhr": "Wetter (Ruhr)",
  delbrueck: "Delbrück",
  "porta-westfalica": "Porta Westfalica",
  wiehl: "Wiehl",
  duelmen: "Dülmen",
  luedinghausen: "Lüdinghausen",
  meckenheim: "Meckenheim",
  kreuztal: "Kreuztal",
  hamminkeln: "Hamminkeln",
  meschede: "Meschede",
  iserlohn: "Iserlohn",
  oelde: "Oelde",
  frechen: "Frechen",
  rheine: "Rheine",
  niederkassel: "Niederkassel",
  toenisvorst: "Tönisvorst",
  bielefeld: "Bielefeld",
  detmold: "Detmold",
  wachtberg: "Wachtberg",
  grevenbroich: "Grevenbroich",
  erkelenz: "Erkelenz",
  hattingen: "Hattingen",
  overath: "Overath",
  warstein: "Warstein",
  "bad-salzuflen": "Bad Salzuflen",
  attendorn: "Attendorn",
  greven: "Greven",
  lippstadt: "Lippstadt",
  dorsten: "Dorsten",
  ennepetal: "Ennepetal",
  velbert: "Velbert",
  dormagen: "Dormagen",
  leverkusen: "Leverkusen",
  meinerzhagen: "Meinerzhagen",
  alfter: "Alfter",
  wilnsdorf: "Wilnsdorf",
  wegberg: "Wegberg",
  siegen: "Siegen",
  werne: "Werne",
  schmallenberg: "Schmallenberg",
  steinhagen: "Steinhagen",
  vreden: "Vreden",
  luebbecke: "Lübbecke",
  witten: "Witten",
  schwelm: "Schwelm",
  steinfurt: "Steinfurt",
  rheinbach: "Rheinbach",
  recklinghausen: "Recklinghausen",
  brilon: "Brilon",
  geldern: "Geldern",
  luedenscheid: "Lüdenscheid",
  telgte: "Telgte",
  lemgo: "Lemgo",
  soest: "Soest",
  engelskirchen: "Engelskirchen",
  wesel: "Wesel",
  xanten: "Xanten",
  remscheid: "Remscheid",
  juelich: "Jülich",
  warburg: "Warburg",
  heiligenhaus: "Heiligenhaus",
  burbach: "Burbach",
  odenthal: "Odenthal",
  moers: "Moers",
  krefeld: "Krefeld",
  viersen: "Viersen",
  minden: "Minden",
  "froendenberg-ruhr": "Fröndenberg / Ruhr",
  lennestadt: "Lennestadt",
  wuelfrath: "Wülfrath",
  hemer: "Hemer",
  kevelaer: "Kevelaer",
  "neunkirchen-seelscheid": "Neunkirchen-Seelscheid",
  siegburg: "Siegburg",
  ahlen: "Ahlen",
  rhede: "Rhede",
  wuerselen: "Würselen",
  beckum: "Beckum",
  loehne: "Löhne",
  paderborn: "Paderborn",
  essen: "Essen",
  senden: "Senden",
  rheinberg: "Rheinberg",
  nottuln: "Nottuln",
  moenchengladbach: "Mönchengladbach",
  burscheid: "Burscheid",
  troisdorf: "Troisdorf",
  bottrop: "Bottrop",
  drensteinfurt: "Drensteinfurt",
  freudenberg: "Freudenberg",
  kuerten: "Kürten",
  juechen: "Jüchen",
  swisttal: "Swisttal",
  "neukirchen-vluyn": "Neukirchen-Vluyn",
  kerpen: "Kerpen",
  versmold: "Versmold",
  hoexter: "Höxter",
  waltrop: "Waltrop",
  stadtlohn: "Stadtlohn",
  aachen: "Aachen",
  erwitte: "Erwitte",
  lindlar: "Lindlar",
  ibbenbueren: "Ibbenbüren",
  "bad-berleburg": "Bad Berleburg",
  halle: "Halle (Westf.)",
  wipperfuerth: "Wipperfürth",
  enger: "Enger",
  bergheim: "Bergheim",
  gevelsberg: "Gevelsberg",
  oerlinghausen: "Oerlinghausen",
  vlotho: "Vlotho",
  finnentrop: "Finnentrop",
  nettetal: "Nettetal",
  hille: "Hille",
  wenden: "Wenden",
  selm: "Selm",
  mechernich: "Mechernich",
  netphen: "Netphen",
  schwalmtal: "Schwalmtal",
  radevormwald: "Radevormwald",
  straelen: "Straelen",
  plettenberg: "Plettenberg",
  hiddenhausen: "Hiddenhausen",
  wuppertal: "Wuppertal",
  ennigerloh: "Ennigerloh",
  "castrop-rauxel": "Castrop-Rauxel",
  kamen: "Kamen",
  kreuzau: "Kreuzau",
  windeck: "Windeck",
  "bad-muenstereifel": "Bad Münstereifel",
  salzkotten: "Salzkotten",
  much: "Much",
  petershagen: "Petershagen",
  bochum: "Bochum",
  holzwickede: "Holzwickede",
  "bad-wuennenberg": "Bad Wünnenberg",
  herzogenrath: "Herzogenrath",
  gummersbach: "Gummersbach",
  huenxe: "Hünxe",
  lengerich: "Lengerich",
  bedburg: "Bedburg",
  heinsberg: "Heinsberg",
  blomberg: "Blomberg",
  "herzebrock-clarholz": "Herzebrock-Clarholz",
  marl: "Marl",
  euskirchen: "Euskirchen",
  brueggen: "Brüggen",
  schermbeck: "Schermbeck",
  simmerath: "Simmerath",
  hoerstel: "Hörstel",
  harsewinkel: "Harsewinkel",
  "monheim-am-rhein": "Monheim am Rhein",
  dortmund: "Dortmund",
  halver: "Halver",
  hoevelhof: "Hövelhof",
  moehnesee: "Möhnesee",
  sendenhorst: "Sendenhorst",
  ascheberg: "Ascheberg",
  nuembrecht: "Nümbrecht",
  gronau: "Gronau (Westf.)",
  stolberg: "Stolberg (Rhld.)",
  "voerde-niederrhein": "Voerde (Niederrhein)",
  rommerskirchen: "Rommerskirchen",
  kirchhundem: "Kirchhundem",
  niederkruechten: "Niederkrüchten",
  zuelpich: "Zülpich",
  dueren: "Düren",
  kerken: "Kerken",
  borchen: "Borchen",
  billerbeck: "Billerbeck",
  weilerswist: "Weilerswist",
  bueren: "Büren",
  marsberg: "Marsberg",
  geilenkirchen: "Geilenkirchen",
  "bad-sassendorf": "Bad Sassendorf",
  hagen: "Hagen",
  neuenkirchen: "Neuenkirchen",
  winterberg: "Winterberg",
  goch: "Goch",
  huellhorst: "Hüllhorst",
  elsdorf: "Elsdorf",
  rees: "Rees",
  oberhausen: "Oberhausen",
  lage: "Lage",
  eschweiler: "Eschweiler",
  datteln: "Datteln",
  hamm: "Hamm",
  raesfeld: "Raesfeld",
  grefrath: "Grefrath",
  brakel: "Brakel",
  hilchenbach: "Hilchenbach",
  reichshof: "Reichshof",
  reken: "Reken",
  ochtrup: "Ochtrup",
  herten: "Herten",
  spenge: "Spenge",
  havixbeck: "Havixbeck",
  alpen: "Alpen",
  langerwehe: "Langerwehe",
  werther: "Werther (Westf.)",
  hueckeswagen: "Hückeswagen",
  werl: "Werl",
  wesseling: "Wesseling",
  monschau: "Monschau",
  rahden: "Rahden",
  kalletal: "Kalletal",
  geseke: "Geseke",
  luenen: "Lünen",
  drolshagen: "Drolshagen",
  ense: "Ense",
  stemwede: "Stemwede",
  velen: "Velen",
  leopoldshoehe: "Leopoldshöhe",
  schalksmuehle: "Schalksmühle",
  olsberg: "Olsberg",
  altenberge: "Altenberge",
  balve: "Balve",
  neuenrade: "Neuenrade",
  "bad-driburg": "Bad Driburg",
  kirchlengern: "Kirchlengern",
  olfen: "Olfen",
  "bad-laasphe": "Bad Laasphe",
  gescher: "Gescher",
  "preussisch-oldendorf": "Preußisch Oldendorf",
  steinheim: "Steinheim",
  neunkirchen: "Neunkirchen",
  wassenberg: "Wassenberg",
  altena: "Altena",
  "kamp-lintfort": "Kamp-Lintfort",
  gladbeck: "Gladbeck",
  baesweiler: "Baesweiler",
  nordkirchen: "Nordkirchen",
  herne: "Herne",
  "uebach-palenberg": "Übach-Palenberg",
  everswinkel: "Everswinkel",
  ostbevern: "Ostbevern",
  nideggen: "Nideggen",
  beverungen: "Beverungen",
  sassenberg: "Sassenberg",
  "horn-bad-meinberg": "Horn-Bad Meinberg",
  eitorf: "Eitorf",
  issum: "Issum",
  wadersloh: "Wadersloh",
  linnich: "Linnich",
  bergneustadt: "Bergneustadt",
  roetgen: "Roetgen",
  kalkar: "Kalkar",
  hueckelhoven: "Hückelhoven",
  lichtenau: "Lichtenau",
  niederzier: "Niederzier",
  lippetal: "Lippetal",
  kierspe: "Kierspe",
  bergkamen: "Bergkamen",
  rosendahl: "Rosendahl",
  kleve: "Kleve",
  mettingen: "Mettingen",
  suedlohn: "Südlohn",
  espelkamp: "Espelkamp",
  anroechte: "Anröchte",
  westerkappeln: "Westerkappeln",
  welver: "Welver",
  "oer-erkenschwick": "Oer-Erkenschwick",
  ruethen: "Rüthen",
  "emmerich-am-rhein": "Emmerich am Rhein",
  "bad-lippspringe": "Bad Lippspringe",
  duisburg: "Duisburg",
  roedinghausen: "Rödinghausen",
  boenen: "Bönen",
  tecklenburg: "Tecklenburg",
  noervenich: "Nörvenich",
  schleiden: "Schleiden",
  ruppichteroth: "Ruppichteroth",
  kall: "Kall",
  "bedburg-hau": "Bedburg-Hau",
  eslohe: "Eslohe (Sauerland)",
  waldbroel: "Waldbröl",
  marienheide: "Marienheide",
  borgholzhausen: "Borgholzhausen",
  huertgenwald: "Hürtgenwald",
  morsbach: "Morsbach",
  nordwalde: "Nordwalde",
  titz: "Titz",
  langenberg: "Langenberg",
  alsdorf: "Alsdorf",
  breckerfeld: "Breckerfeld",
  borgentreich: "Borgentreich",
  extertal: "Extertal",
  heek: "Heek",
  heiden: "Heiden",
  legden: "Legden",
  sonsbeck: "Sonsbeck",
  merzenich: "Merzenich",
  lotte: "Lotte",
  werdohl: "Werdohl",
  bestwig: "Bestwig",
  gelsenkirchen: "Gelsenkirchen",
  "wickede-ruhr": "Wickede (Ruhr)",
  recke: "Recke",
  schoeppingen: "Schöppingen",
  wachtendonk: "Wachtendonk",
  luegde: "Lügde",
  lienen: "Lienen",
  gangelt: "Gangelt",
  altenbeken: "Altenbeken",
  herscheid: "Herscheid",
  aldenhoven: "Aldenhoven",
  hopsten: "Hopsten",
  vettweiss: "Vettweiß",
  wettringen: "Wettringen",
  schlangen: "Schlangen",
  uedem: "Uedem",
  waldfeucht: "Waldfeucht",
  hellenthal: "Hellenthal",
  saerbeck: "Saerbeck",
  isselburg: "Isselburg",
  nettersheim: "Nettersheim",
  ladbergen: "Ladbergen",
  erndtebrueck: "Erndtebrück",
  "nachrodt-wiblingwerde": "Nachrodt-Wiblingwerde",
  medebach: "Medebach",
  barntrup: "Barntrup",
  blankenheim: "Blankenheim",
  laer: "Laer",
  rheurdt: "Rheurdt",
  "schieder-schwalenberg": "Schieder-Schwalenberg",
  selfkant: "Selfkant",
  doerentrup: "Dörentrup",
  willebadessen: "Willebadessen",
  weeze: "Weeze",
  nieheim: "Nieheim",
  inden: "Inden",
  beelen: "Beelen",
  horstmar: "Horstmar",
  augustdorf: "Augustdorf",
  marienmuenster: "Marienmünster",
  kranenburg: "Kranenburg",
  hallenberg: "Hallenberg",
  metelen: "Metelen",
  dahlem: "Dahlem",
  heimbach: "Heimbach",
};

export function isCitySlug(slug: string): slug is CitySlug {
  return CITY_SET.has(slug);
}

export function cityLabel(slug: CitySlug) {
  return CITY_LABELS[slug];
}
